export const COMMIT = {
  UPDATE_STEP: "UPDATE_STEP",
  IMG_PATH: "IMG_PATH",
  LAST_LOCALE_MESSAGE: "LAST_LOCALE_MESSAGE"
};

export const ROUTE = {
  MY_DATA: "MY_DATA",
  ORDER_CONFIRM: "ORDER_CONFIRM",
}

export const REDIRECT_TIMEOUT = 3000;
