export const COMMIT = {
  NEXT_STEP: "NEXT_STEP",
  PREVIOUS_STEP: "PREVIOUS_STEP",
  IMG_PATH: "IMG_PATH",
  LAST_LOCALE_MESSAGE: "LAST_LOCALE_MESSAGE"
};

export const ROUTE = {
  MY_DATA: "MY_DATA",
  PAYMENT: "PAYMENT",
  ORDER_CONFIRM: "ORDER_CONFIRM",
}

export const REDIRECT_TIMEOUT = 3000;
